spring:
  application:
    name: store
  datasource:
    url: jdbc:postgresql://localhost:5432/mydb
    username: myuser
    password: mypass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    user:
      name: user
      password: pass
aws:
  s3:
    bucket-name: xu-store-images
    region: us-east-2
  access-key:
  secret-key:
  cloudfront:
    base-url: https://d9x4fl33eon73.cloudfront.net