server:
  port: 5000
jwt:
  secret: ${JWT_SECRET}
  expiration-period: 86400000 # in milliseconds (24 hours)
spring:
  application:
    name: store
  datasource:
    url: ${DB_URL}
    driver-class-name: org.postgresql.Driver
    username:  ${DB_USERNAME}
    password:  ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 2
      minimum-idle: 0             # ❗ Don't hold idle connections
      idle-timeout: 30000         # 30s, close idle connections quickly
      max-lifetime: 60000         # 60s, close old connections
      connection-timeout: 10000   # Fail fast if DB not responsive
      auto-commit: false          # Avoid unnecessary commits
      pool-name: NeonHikariPool
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        connection:
          release_mode: after_transaction  # Close DB connection ASAP after transaction
  security:
    user:
      name: ${SPRING_SECURITY_USERNAME}
      password: ${SPRING_SECURITY_PASSWORD}
aws:
  s3:
    bucket-name: xu-store-images
    region: us-east-2
  access-key: ${AWS_ACCESS_KEY_ID}
  secret-key: ${AWS_SECRET_ACCESS_KEY}
  cloudfront:
    base-url: ${CLOUDFRONT_BASE_URL}